spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: 7JWI64WV64KY64qQ7IKs7LCo7IS466+464KY7JW87JWI64WV64KY64qQ7IKs7LCo7IS466+464KY7JW87JWI64WV64KY64qQ7IKs7LCo7IS466+464KY7JW8